// This file is generated by Slice Machine. Update with care!

import CategoryOverview from './CategoryOverview';
import ContactForm from './ContactForm';
import Image from './Image';
import Quote from './Quote';
import Text from './Text';

export {
	CategoryOverview,
	ContactForm,
	Image,
	Quote,
	Text,
};

export const components = {
	category_overview: CategoryOverview,
	contact_form: ContactForm,
	image: Image,
	quote: Quote,
	text: Text,
};
